//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceFile
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFile.IServiceFile")]
    public interface IServiceFile
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/UploadFile", ReplyAction="http://tempuri.org/IServiceFile/UploadFileResponse")]
        bool UploadFile(byte[] fileBytes, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/UploadFile", ReplyAction="http://tempuri.org/IServiceFile/UploadFileResponse")]
        System.Threading.Tasks.Task<bool> UploadFileAsync(byte[] fileBytes, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/DownloadFile", ReplyAction="http://tempuri.org/IServiceFile/DownloadFileResponse")]
        byte[] DownloadFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFile/DownloadFile", ReplyAction="http://tempuri.org/IServiceFile/DownloadFileResponse")]
        System.Threading.Tasks.Task<byte[]> DownloadFileAsync(string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServiceFileChannel : ServiceFile.IServiceFile, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServiceFileClient : System.ServiceModel.ClientBase<ServiceFile.IServiceFile>, ServiceFile.IServiceFile
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceFileClient() : 
                base(ServiceFileClient.GetDefaultBinding(), ServiceFileClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceFile.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceFileClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceFileClient.GetBindingForEndpoint(endpointConfiguration), ServiceFileClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceFileClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceFileClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceFileClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceFileClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceFileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool UploadFile(byte[] fileBytes, string fileName)
        {
            return base.Channel.UploadFile(fileBytes, fileName);
        }
        
        public System.Threading.Tasks.Task<bool> UploadFileAsync(byte[] fileBytes, string fileName)
        {
            return base.Channel.UploadFileAsync(fileBytes, fileName);
        }
        
        public byte[] DownloadFile(string fileName)
        {
            return base.Channel.DownloadFile(fileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> DownloadFileAsync(string fileName)
        {
            return base.Channel.DownloadFileAsync(fileName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceFile))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceFile))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57401/ServiceFile.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceFileClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceFile);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceFileClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceFile);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceFile,
        }
    }
}
